### ISSUE TITLE
Mod not showing up

### ISSUE THREAD

**Issue by annitya** [onimp/oni_multiplayer#121]
Hi!

I installed the mod as instructed, but on one of the PCs it doesn't show up for some reason.
The game was originally installed on the d-drive, but even after moving the installation/reinstalling the list is still empty.

Any idea what might have gone wrong?

PS: Thanks for your awesome work <3

**Comment by zuev93** [comment]
Please take a look at https://github.com/zuev93/oni_multiplayer/issues/114
