### ISSUE TITLE
Check not deterministic chores (one using Random)

### ISSUE THREAD

**Issue by zuev93** [onimp/oni_multiplayer#13]
Example of such chores:
IdleChore, MoveToSafetyChore, etc...

**Comment by Ceron257** [comment]
Here are chores that use `Unity.Random`:

* `AggressiveChore`
  *  Used to flip a coin to decide whether a stressed out dupe destroys walls or buildings
* `BansheeChore`
  * determines the maximum pathfinding cost of
    * where to wander in the wandering state
    * where to go when no other dupe to wail at is found
* `FoodFightChore` used to determine
  * what other dupe to attack
  * whether to flee or cringe when being hit
* `IdleChore`
  * Used to determine the timespan after which the state transitions from `onfloor` to `idleMove` or from `onladder` to `idleMove`
* `MingleChore`
  * determines the time the dupe is in the `onfloor` state before the chore succeeds
