### ISSUE TITLE
Crash on joining to host

### ISSUE THREAD

**Issue by amors10** [onimp/oni_multiplayer#160]
Game crashes on joining computer when first joining to host. Tried with both computers hosting the game and crashed in both instances. Confirmed build IDs are the same between both sessions.

Log: 
SerializationException: Unable to load type MultiplayerMod.Multiplayer.Commands.State.SyncSharedState required for deserialization.

System.Runtime.Serialization.ObjectManager.CompleteObject (System.Runtime.Serialization.ObjectHolder holder, System.Boolean bObjectFullyComplete) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups (System.Runtime.Serialization.ObjectHolder holder) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.ObjectManager.RegisterObject (System.Object obj, System.Int64 objectID, System.Runtime.Serialization.SerializationInfo info, System.Int64 idOfContainingObj, System.Reflection.MemberInfo member, System.Int32[] arrayIndex) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject (System.Object obj, System.Runtime.Serialization.Formatters.Binary.ParseRecord pr, System.Runtime.Serialization.Formatters.Binary.ParseRecord objectPr, System.Boolean bIsString) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject (System.Object obj, System.Runtime.Serialization.Formatters.Binary.ParseRecord pr, System.Runtime.Serialization.Formatters.Binary.ParseRecord objectPr) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd (System.Runtime.Serialization.Formatters.Binary.ParseRecord pr) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse (System.Runtime.Serialization.Formatters.Binary.ParseRecord pr) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize (System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser serParser, System.Boolean fCheck, System.Boolean isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck, System.Boolean isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream) (at <695d1cc93cca45069c528c15c9fdd749>:0)
MultiplayerMod.Platform.Steam.Network.Messaging.NetworkSerializer.Deserialize (MultiplayerMod.Platform.Steam.Network.Messaging.INetworkMessageHandle message) (at <ec88ba9246664ff2b786e27e4c05f109>:0)
MultiplayerMod.Platform.Steam.Network.Messaging.NetworkMessageProcessor.Process (System.UInt32 clientId, MultiplayerMod.Platform.Steam.Network.Messaging.INetworkMessageHandle handle) (at <ec88ba9246664ff2b786e27e4c05f109>:0)
MultiplayerMod.Platform.Steam.Network.SteamClient.ReceiveCommands () (at <ec88ba9246664ff2b786e27e4c05f109>:0)
MultiplayerMod.Platform.Steam.Network.SteamClient.Tick () (at <ec88ba9246664ff2b786e27e4c05f109>:0)
MultiplayerMod.Platform.Steam.Network.Components.SteamClientComponent.Update () (at <ec88ba9246664ff2b786e27e4c05f109>:0)

Build: U47-562984-V

**Comment by zuev93** [comment]
It seems like you are using different version on different clients. Please make sure that you are using the same version

**Comment by amors10** [comment]
Copy, will try and report back. Thanks!

**Comment by zuev93** [comment]
Hi @amors10 any updates on your side?

**Comment by polycone** [comment]
Closing this as no additional input was provided.
