### ISSUE TITLE
Host Crashes when claiming care package from printing pod

### ISSUE THREAD

**Issue by Levathan21** [onimp/oni_multiplayer#182]
Tryed to claim care pack and the game completely crashed on the host's end but other users did not crash

NullReferenceException: Object reference not set to an instance of an object

MultiplayerMod.Game.Mechanics.Minions.MinionIdentityExtensions.GetMultiplayerInstance (MinionIdentity identity) (at <9208d912d65a4ea6979582fb9a2587e6>:0)
MultiplayerMod.Game.Mechanics.Printing.TelepadEvents+<>c__DisplayClass7_0.<OnAcceptDelivery>b__0 () (at <9208d912d65a4ea6979582fb9a2587e6>:0)
MultiplayerMod.Core.Patch.PatchControl.RunIfEnabled (System.Action action) (at <9208d912d65a4ea6979582fb9a2587e6>:0)
MultiplayerMod.Game.Mechanics.Printing.TelepadEvents.OnAcceptDelivery (Telepad telepad, ITelepadDeliverable deliverable, UnityEngine.GameObject gameObject) (at <9208d912d65a4ea6979582fb9a2587e6>:0)
(wrapper dynamic-method) Telepad.Telepad.OnAcceptDelivery_Patch0(Telepad,ITelepadDeliverable)
ImmigrantScreen.OnProceed () (at <cd4b9bd5aa6c4ec38ec00dca1dc79105>:0)
CharacterSelectionController.<EnableProceedButton>b__32_0 () (at <cd4b9bd5aa6c4ec38ec00dca1dc79105>:0)
KButton.SignalClick (KKeyCode btn) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U47-562984-VD

**Comment by tedens** [comment]
Also getting same error on cycle 12.
