### ISSUE TITLE
Crash when selecting critter filter on critter drop off building

### ISSUE THREAD

**Issue by tedens** [onimp/oni_multiplayer#191]
I specifically selected various types of hatches. 

NullReferenceException

MultiplayerMod.Multiplayer.Objects.ComponentReferenceExtensions.GetReference (KMonoBehaviour component) (at <afddccdef4fc4478bb3665237e8644fa>:0)
MultiplayerMod.Game.Mechanics.Objects.ObjectEvents+<>c__DisplayClass5_0.<ObjectEventsPostfix>b__0 () (at <afddccdef4fc4478bb3665237e8644fa>:0)
MultiplayerMod.Core.Patch.PatchControl.RunIfEnabled (System.Action action) (at <afddccdef4fc4478bb3665237e8644fa>:0)
MultiplayerMod.Game.Mechanics.Objects.ObjectEvents.ObjectEventsPostfix (KMonoBehaviour __instance, System.Reflection.MethodBase __originalMethod, System.Object[] __args) (at <afddccdef4fc4478bb3665237e8644fa>:0)
(wrapper dynamic-method) FixedCapturePoint+Instance.FixedCapturePoint+Instance.ICheckboxControl.SetCheckboxValue_Patch1(FixedCapturePoint/Instance,bool)
SingleCheckboxSideScreen.OnValueChanged (System.Boolean value) (at <cd4b9bd5aa6c4ec38ec00dca1dc79105>:0)
Util.Signal[T] (System.Action`1[T] action, T parameter) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
KToggle.OnValueChanged (System.Boolean value) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
KToggle.set_isOn (System.Boolean value) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
SingleCheckboxSideScreen.SetTarget (UnityEngine.GameObject target) (at <cd4b9bd5aa6c4ec38ec00dca1dc79105>:0)
DetailsScreen.Refresh (UnityEngine.GameObject go) (at <cd4b9bd5aa6c4ec38ec00dca1dc79105>:0)
RootMenu.Refresh () (at <cd4b9bd5aa6c4ec38ec00dca1dc79105>:0)
RootMenu.OnSelectObject (System.Object data) (at <cd4b9bd5aa6c4ec38ec00dca1dc79105>:0)
EventSystem.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
KMonoBehaviour.Trigger (System.Int32 hash, System.Object data) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
SelectTool.Select (KSelectable new_selected, System.Boolean skipSound) (at <cd4b9bd5aa6c4ec38ec00dca1dc79105>:0)
SelectTool.OnLeftClickDown (UnityEngine.Vector3 cursor_pos) (at <cd4b9bd5aa6c4ec38ec00dca1dc79105>:0)
PlayerController.OnKeyDown (KButtonEvent e) (at <cd4b9bd5aa6c4ec38ec00dca1dc79105>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
KInputHandler.HandleEvent (KInputEvent e) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
KInputController.Dispatch () (at <0f4b778ef79c497e89f6ee18303840cf>:0)
KInputManager.Dispatch () (at <0f4b778ef79c497e89f6ee18303840cf>:0)
KInputManager.Update () (at <0f4b778ef79c497e89f6ee18303840cf>:0)
GameInputManager.Update () (at <0f4b778ef79c497e89f6ee18303840cf>:0)
Global.Update () (at <cd4b9bd5aa6c4ec38ec00dca1dc79105>:0)

Build: U47-562984-V

**Comment by zuev93** [comment]
Thanks for the finding!
Fix is merged and will be released in the next update.
