### ISSUE TITLE
Cursor bug

### ISSUE THREAD

**Issue by Azurz** [onimp/oni_multiplayer#243]
![image](https://github.com/onimp/oni_multiplayer/assets/35930914/9bb97f5e-fbc0-4afd-975a-dc7b0f117ae9)
When there are more than 2 people, the cursor display bugs.

**Comment by Azurz** [comment]
The bug was that visually, we no longer see the cursors of other people moving, however, we see our cursor in the correct position.

**Comment by EthanCannoy** [comment]
Having similar issues here as well. Sometimes one person has working cursor, sometimes none, somtimes it swaps names. It's all over the place once you get 3+ people.
