### ISSUE TITLE
MPNI inspiration ?

### ISSUE THREAD

**Issue by 1000i100** [onimp/oni_multiplayer#348]
Hi, i've discovered a previous attempt to make a multiplayer mod for ONI : https://github.com/MPNI/MPNI are you aware of it ? Is there concept, or code fragment, or contributor that could be usefull for this project ?

**Comment by zuev93** [comment]
Hi,

Thanks for highlighting this repo.
We've checked it and as far as I can see there is not so much to have it merged.
The repo seems to have base networking and steam integration set up as well as a sync of player camera.

In that sense I feel like our existing features already covers those things.

However thanks for bringing this up!
