### ISSUE TITLE
Handle ESC vs pause click

### ISSUE THREAD

**Issue by skrilax91** [onimp/oni_multiplayer#36]
When i pause the game on host, the client don't pause and I can see his cursor on my pause menu

**Comment by KAINYMLP** [comment]
I found, being a non-host, that when I press ESC the game is paused, but the game of a friend (host) continues. After that, we are out of sync

**Comment by skrilax91** [comment]
Yes I found it also, I think that it should be good to let the game continue if we go to the ESC menu, to avoid unexpected game pauses for other clients
