### ISSUE TITLE
Crash on joining game while on Dupe selection

### ISSUE THREAD

**Issue by kepper104** [onimp/oni_multiplayer#77]
### Problem
If a client tries to join the game while the host has just created it and is still selecting duplicants, the game crashes.
### Stack Trace:
```
NullReferenceException: Object reference not set to an instance of an object

Timelapser+<Render>d__29.MoveNext () (at <1f4c5a7d658c4522888fade7e74323ad>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <72b60a3dd8cd4f12a155b761a1af9144>:0)

Build: U46-552078-V
```
### Steps to reproduce:

- Host starts a new multiplayer game (from the menu) and wait until the map generates
- The host is currently on dupe selection screen
- The client tries to join using the steam overlay
- The game crashes for host, the client spawns on the map without dupes...

**Comment by zuev93** [comment]
Thanks for the report and nice task description!
