### ISSUE TITLE
Inform others if someone is joining/loading/syncing

### ISSUE THREAD

**Issue by zuev93** [onimp/oni_multiplayer#86]
E.g. every morning host game just pauses while other are syncing, however its not clear for the host what is happening.

The same happens when new player joins - game just pauses for everyone except new player..

**Comment by tinetik** [comment]
@zuev93 Were you thinking more of a small dot notification for this, a big alert that takes up the majority of the screen, or an interactive menu where a host could accept/reject the join attempt?
