### ISSUE TITLE
Install script does not work for non C:/ documents location

### ISSUE THREAD

**Issue by edunad** [onimp/oni_multiplayer#87]
I've noticed the install script does not work for users where the documents folder has been moved from `C:/`

The following script will fix it :
```
@echo off

FOR /F "tokens=2* skip=2" %%a in ('reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "personal"') do set DocumentsFolder=%%b

echo "Installing multiplayer mod in folder: %DocumentsFolder%\Documents\Klei\OxygenNotIncluded\mods\Local\MultiplayerMod\"
xcopy /s .\MultiplayerMod %DocumentsFolder%\Documents\Klei\OxygenNotIncluded\mods\Local\MultiplayerMod\
```

**Comment by zuev93** [comment]
Thanks for the provided script!

Also do not hesitate to create fork and add your script to the repo (if you'd like to )

**Comment by edunad** [comment]
> Thanks for the provided script!
> 
> Also do not hesitate to create fork and add your script to the repo (if you'd like to )

Wanted to create a fork, but wasn't sure where the script generation was happening, haven't delved into the code that much yet xD

**Comment by zuev93** [comment]
I haven't added a script to the build pipeline yet :)
So I've just manually added the bat file while preparing release zip file.

**Comment by edunad** [comment]
I'm attempting to setup the CI/CD using github actions, i'll add the script there :)

**Comment by edunad** [comment]
@zuev93 I've tried a few things to get the github actions working, but, I'm not sure if we are allowed to copy over the oni dlls (specifically Assembly-CSharp & Assembly-CSharp-firstpass) and place them somewhere in a folder for development 🤔.

**Comment by zuev93** [comment]
Me neither.

On some Klei forum I've seen messages that the KLEI are fine with modders decompiling Asssembly-CSharp & firstpass.
However I'd avoid copy pasting their dlls to game repo due to license and outdating reasons.

Is it feasible to setup custom goal in csproj/solution files to have zip file created upon release build/other action?
Because dropping ready zip archive to github is not a big deal.

**Comment by edunad** [comment]
I'll give it a try, worst case it's a `.bat` that compiles, zips and uploads to github for you

**Comment by zuev93** [comment]
I've added your bat script to the repo. So closing this issue for now.
